# Generated by Django 5.2.16 on 2026-08-04 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('active', 'Actif'), ('inactive', 'Inactif')], default='pending', max_length=10, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire')),
            ],
            options={
                'verbose_name': 'personnage',
                'verbose_name_plural': 'personnages',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('owner', 'name'), name='unique_character_name_per_owner')],
            },
        ),
    ]
