# Generated by Django 5.2.16 on 2026-08-04 21:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='character',
            name='experience',
            field=models.PositiveIntegerField(default=0, verbose_name='expérience'),
        ),
        migrations.AddField(
            model_name='character',
            name='level',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='niveau'),
        ),
    ]
