# Generated by Django 5.2.16 on 2026-08-04 21:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_character_description_character_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='agility',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='agilité'),
        ),
        migrations.AddField(
            model_name='character',
            name='charisma',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='charisme'),
        ),
        migrations.AddField(
            model_name='character',
            name='endurance',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='endurance'),
        ),
        migrations.AddField(
            model_name='character',
            name='intelligence',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='intelligence'),
        ),
        migrations.AddField(
            model_name='character',
            name='perception',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='perception'),
        ),
        migrations.AddField(
            model_name='character',
            name='strength',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='force'),
        ),
        migrations.AddField(
            model_name='character',
            name='willpower',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='volonté'),
        ),
    ]
