# Generated by Django 5.2.16 on 2026-08-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_character_agility_character_charisma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='current_health',
            field=models.PositiveIntegerField(default=0, verbose_name='PV actuels'),
        ),
        migrations.AddField(
            model_name='character',
            name='current_mana',
            field=models.PositiveIntegerField(default=0, verbose_name='mana actuel'),
        ),
        migrations.AddField(
            model_name='character',
            name='current_stamina',
            field=models.PositiveIntegerField(default=0, verbose_name='endurance actuelle'),
        ),
    ]
