# Generated by Django 5.2.16 on 2026-08-06 19:28

import django.db.models.functions.text
import django.db.models.lookups
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_character_current_health_character_current_mana_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='character',
            name='unique_character_name_per_owner',
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.UniqueConstraint(models.F('owner'), django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name')), name='unique_character_name_ci_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.GreaterThanOrEqual(django.db.models.functions.text.Length(django.db.models.functions.text.Trim(models.F('name'))), models.Value(2)), name='character_name_min_2_chars'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.LessThanOrEqual(django.db.models.functions.text.Length(models.F('description')), models.Value(2000)), name='character_description_max_2000_chars'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(condition=models.Q(('level__gte', 1)), name='character_level_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(condition=models.Q(('strength__gte', 1), ('agility__gte', 1), ('endurance__gte', 1), ('intelligence__gte', 1), ('perception__gte', 1), ('willpower__gte', 1), ('charisma__gte', 1)), name='character_stats_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(condition=models.Q(('experience__gte', 0), ('current_health__gte', 0), ('current_stamina__gte', 0), ('current_mana__gte', 0)), name='character_resources_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'active', 'inactive'))), name='character_status_valid'),
        ),
    ]
